### ISSUE TITLE
Do you know how to disable signature check for loading modules?

### ISSUE THREAD

**Issue by romanovj** [wuxianlin/build_magisk_vivo#6]
My phone is vivo y31 2021. In order to dig kernel I used radare and r2ghidra in termux.

I patched kernel so is_module_sig_enforced and module_sig_check  always returns 0, but it didn't work.

Do you have ideas how to properly disable it? 

UPD. nevermind I just need to sign module with whatever signature

**Comment by wuxianlin** [comment]
I haven't tried disable signature check for the kernel module. 
You can try if your method works on other Android phones like pixel, or look up vivo's kernel source code to see if related functions have been modified, or build your own kernel using vivo's source code.

**Comment by romanovj** [comment]
> I haven't tried disable signature check for the kernel module. You can try if your method works on other Android phones like pixel, or look up vivo's kernel source code to see if related functions have been modified, or build your own kernel using vivo's source code.

I was able to load bbr and hybla tcp congestion control, so this method works on vivo kernels (at least.on 4.19)

One more question, do you know how to find which instructions reads string "/system"?

**Comment by romanovj** [comment]
I developed patches for unblocking SU, should be one hit per patch

./magiskboot hexpatch kernel 00010034a000805221008052 20000034a000805221008052

./magiskboot hexpatch kernel e0000034a000805221008052 20000034a000805221008052

**Comment by romanovj** [comment]
Patching vrr_do_mount_check_before_mount removed all restrictions for mount and remount

magiskboot hexpatch kernel 085040b9680e0034 085040b9680E0035

**Comment by wuxianlin** [comment]
You can try this patch to fix system remount:https://github.com/wuxianlin/build_magisk_vivo/blob/master/patches/Magisk/patch_vivo_do_mount_check.diff
